

stopout("Something goes wrong outside of testthat")

test_that("a passing test", {
  expect_equal(1+1, 2)
})

test_that("a passing test", {
  expect_equal(1+1, 2)
})
